parameters:
  HGT: [10, 15.5]
  Lstr: [0, 1]
  THK: [0.25, 0.6]
  ANG: [-10, 10]
  CVT: [0.1, 0.8]
  LAS: [0.2, 1.0]

objectives:
  - -LMN_open^2
  - LMN_closed
  - Slim - Smax
  - -1/(HELI^2)

problem_definition:
  name: otp_geom
  position: mitr
  problem_name: leaflet_contact
  DIA: 26
  Lift: 0
  SEC: 119
  mesh_step: 0.4
  material:
    material_definition_type: ortho
    material_name: Ortho material
    poisson_coeff: 0.495
    Dens: 1.02e-9
    EM: 1.88
    s_lim: 9.9
    material_csv_path: bp.csv
    ortho_coeffs_E:
      - 20
      - 60
      - 60
    ortho_coeffs_poisson:
      - 0.3
      - 0.3
      - 0.3
      
Abaqus:
  abq_cpus: 3
  tangent_behavior: 1
  normal_behavior: 0.2


optimizer:
  pop_size: 90
  offsprings: 10
  crossover_chance: 0.9
  mutation_chance: 0.3
  crossover_eta: 50
  mutation_eta: 100
  termination_parameters:
    xtol: 1e-4
    cvtol: 1e-6
    ftol: 0.0025
    period: 5
    n_max_gen: 2000
    n_max_evals: 100000

hydra:
  run:
    dir: .


